version: '3'

services:
###> doctrine/doctrine-bundle ###
  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: news_db
      # You should definitely change the password in production
      MYSQL_USER: newsdb_user
      MYSQL_PASSWORD: N3w$@00
      MYSQL_ROOT_PASSWORD: N3w$@00
      
    ports:
      - "3306:3306"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

# volumes:
#   - db_data:/var/lib/mysql
###> doctrine/doctrine-bundle ###
  # database_data:
###< doctrine/doctrine-bundle ###
